version: '3.9'

services:
  fastapi_app:
    build: .
    container_name: fastapi_app
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    command: uvicorn application:app --host 0.0.0.0 --port 9000 --reload
